# Etapa de compilación
FROM alpine:latest AS build

# Actualizar e instalar dependencias necesarias
RUN apk update && \
    apk add openjdk17 bash wget unzip

# Copiar el código fuente
COPY . .

# Dar permisos de ejecución al wrapper de Gradle
RUN chmod +x ./gradlew

# Compilar el proyecto
RUN ./gradlew bootJar --no-daemon

# Etapa de producción
FROM openjdk:17-alpine

# Exponer el puerto
EXPOSE 9000

# Copiar el archivo JAR desde la etapa de compilación
COPY --from=build /build/libs/buen-sabor-back-0.0.1-SNAPSHOT.jar /app.jar

# Comando de inicio
ENTRYPOINT ["java", "-jar", "/app.jar"]
