services:
  - type: web
    name: my-spring-boot-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "./gradlew bootJar"
    startCommand: "java -jar /app.jar"
    port: 9000
